<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CountriesTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('countries')->insert([
            [
                'iso_code' => 'AF',
                'name' => 'Afghanistan',
                'default_locale' => 'fa-AF',
                'currency_code' => 'AFN',
                'phone_code' => '+93',
                'timezone' => 'Asia/Kabul',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'iso_code' => 'AL',
                'name' => 'Albania',
                'default_locale' => 'sq-AL',
                'currency_code' => 'ALL',
                'phone_code' => '+355',
                'timezone' => 'Europe/Tirane',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'iso_code' => 'DZ',
                'name' => 'Algeria',
                'default_locale' => 'ar-DZ',
                'currency_code' => 'DZD',
                'phone_code' => '+213',
                'timezone' => 'Africa/Algiers',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'iso_code' => 'AR',
                'name' => 'Argentina',
                'default_locale' => 'es-AR',
                'currency_code' => 'ARS',
                'phone_code' => '+54',
                'timezone' => 'America/Argentina/Buenos_Aires',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'iso_code' => 'AU',
                'name' => 'Australia',
                'default_locale' => 'en-AU',
                'currency_code' => 'AUD',
                'phone_code' => '+61',
                'timezone' => 'Australia/Sydney',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'iso_code' => 'BD',
                'name' => 'Bangladesh',
                'default_locale' => 'bn-BD',
                'currency_code' => 'BDT',
                'phone_code' => '+880',
                'timezone' => 'Asia/Dhaka',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'iso_code' => 'BE',
                'name' => 'Belgium',
                'default_locale' => 'nl-BE',
                'currency_code' => 'EUR',
                'phone_code' => '+32',
                'timezone' => 'Europe/Brussels',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'iso_code' => 'BR',
                'name' => 'Brazil',
                'default_locale' => 'pt-BR',
                'currency_code' => 'BRL',
                'phone_code' => '+55',
                'timezone' => 'America/Sao_Paulo',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'iso_code' => 'CA',
                'name' => 'Canada',
                'default_locale' => 'en-CA',
                'currency_code' => 'CAD',
                'phone_code' => '+1',
                'timezone' => 'America/Toronto',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'iso_code' => 'CN',
                'name' => 'China',
                'default_locale' => 'zh-CN',
                'currency_code' => 'CNY',
                'phone_code' => '+86',
                'timezone' => 'Asia/Shanghai',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'iso_code' => 'FR',
                'name' => 'France',
                'default_locale' => 'fr-FR',
                'currency_code' => 'EUR',
                'phone_code' => '+33',
                'timezone' => 'Europe/Paris',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'iso_code' => 'DE',
                'name' => 'Germany',
                'default_locale' => 'de-DE',
                'currency_code' => 'EUR',
                'phone_code' => '+49',
                'timezone' => 'Europe/Berlin',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'iso_code' => 'IN',
                'name' => 'India',
                'default_locale' => 'en-IN',
                'currency_code' => 'INR',
                'phone_code' => '+91',
                'timezone' => 'Asia/Kolkata',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'iso_code' => 'ID',
                'name' => 'Indonesia',
                'default_locale' => 'id-ID',
                'currency_code' => 'IDR',
                'phone_code' => '+62',
                'timezone' => 'Asia/Jakarta',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'iso_code' => 'IT',
                'name' => 'Italy',
                'default_locale' => 'it-IT',
                'currency_code' => 'EUR',
                'phone_code' => '+39',
                'timezone' => 'Europe/Rome',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'iso_code' => 'JP',
                'name' => 'Japan',
                'default_locale' => 'ja-JP',
                'currency_code' => 'JPY',
                'phone_code' => '+81',
                'timezone' => 'Asia/Tokyo',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'iso_code' => 'LK',
                'name' => 'Sri Lanka',
                'default_locale' => 'si-LK',
                'currency_code' => 'LKR',
                'phone_code' => '+94',
                'timezone' => 'Asia/Colombo',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'iso_code' => 'MY',
                'name' => 'Malaysia',
                'default_locale' => 'en-MY',
                'currency_code' => 'MYR',
                'phone_code' => '+60',
                'timezone' => 'Asia/Kuala_Lumpur',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'iso_code' => 'NL',
                'name' => 'Netherlands',
                'default_locale' => 'nl-NL',
                'currency_code' => 'EUR',
                'phone_code' => '+31',
                'timezone' => 'Europe/Amsterdam',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'iso_code' => 'NZ',
                'name' => 'New Zealand',
                'default_locale' => 'en-NZ',
                'currency_code' => 'NZD',
                'phone_code' => '+64',
                'timezone' => 'Pacific/Auckland',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'iso_code' => 'PK',
                'name' => 'Pakistan',
                'default_locale' => 'ur-PK',
                'currency_code' => 'PKR',
                'phone_code' => '+92',
                'timezone' => 'Asia/Karachi',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'iso_code' => 'SG',
                'name' => 'Singapore',
                'default_locale' => 'en-SG',
                'currency_code' => 'SGD',
                'phone_code' => '+65',
                'timezone' => 'Asia/Singapore',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'iso_code' => 'GB',
                'name' => 'United Kingdom',
                'default_locale' => 'en-GB',
                'currency_code' => 'GBP',
                'phone_code' => '+44',
                'timezone' => 'Europe/London',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'iso_code' => 'US',
                'name' => 'United States',
                'default_locale' => 'en-US',
                'currency_code' => 'USD',
                'phone_code' => '+1',
                'timezone' => 'America/New_York',
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
